-- LuaLine setting
-- local status_ok, lualine = pcall(require, 'lualine')
-- if (not status_ok) then return end
-- 
-- lualine.setup {
--   options = {
--     globalstatus = true,
--     -- theme = 'powerline_dark'
--     -- theme = 'molokai'
--     theme = 'nightfly'
--   },
-- }
