-- local status_ok, null_ls = pcall(require, "null-ls")
-- if (not status_ok) then return end
--
-- null_ls.setup({
--   sources = {
--     -- For Lua
--     null_ls.builtins.formatting.stylua,
--     null_ls.builtins.diagnostics.eslint,
--     null_ls.builtins.completion.spell,
--
--     -- Fortran
--     null_ls.builtins.formatting.fprettify,
--     -- null_ls.builtins.diagnostics.fortls,
--   },
-- })
