import = ["/Users/shinya/.config/alacritty/themes/monokai_classic.toml"]

[env]
TERM = "alacritty"

[font]
size = 12.5

[font.normal]
# family = "CodeNewRoman Nerd Font"
family = "UDEV Gothic 35NF"
style = "Regular"

[font.offset]
x = 0
y = 0

# [[keyboard.bindings]]
# chars = '\'
# key = "Yen"
#
# [[keyboard.bindings]]
# chars = "¥"
# key = "Yen"
# mods = "Alt"
#
# [[keyboard.bindings]]
# action = "ToggleSimpleFullscreen"
# key = "Return"
# mods = "Command"

[scrolling]
history = 10000

[shell]
args = ["--login", "-l", "-c", "tmux a -t default || tmux new -s default"]
program = "/bin/zsh"

[window]
opacity = 0.9
